version: '3.8'

services:
  postgres-local:
    image: postgres:14.3
    container_name: postgres-local
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/initialise_tables.sql:/docker-entrypoint-initdb.d/initialise_tables.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root